#!/bin/bash
# @author Zachary Wartell
# @brief a hack script
#
# TODO
#
# - [someday-maybe] port to python
#
# RESOURCES:
# - https://man7.org/linux/man-pages/man1/getopts.1p.html 
# - https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f

VCPKG_ROOT=/c/vkpkg
LIBRARY=vrpn
SRC_DIR=0d99f50601-340a543fbb

init ()
{
	# Create temp git repo for facilitating generation of git diff patches
	pushd "$VCPKG_ROOT/buildtrees/$LIBRARY/src/$SRC_DIR"
	git init
	git add *
	git commit -m '-vcpkg-helper:  temp git repo for facilitating generation of git diff patches'
	popd
}

generate_patches ()
{
    echo generate_patches
	FILES=`git status | grep modified:`
	echo $FILES
}

dry_run=

PARAMS=""
while (( "$#" )); do
    case "$1" in
        --dry-run)
            dry_run=1
            shift
            ;;
        --generate-patches)
            generate_patches
            exit 0
            ;;
        -*|--*=) # unsupported flags
            echo "Error: Unsupported flag $1" >&2
            exit 1
            ;;
        *) # preserve positional arguments
            PARAMS="$PARAMS $1"
            shift
            ;;
    esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"
